//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2_201700841.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_IPC2 : DbContext
    {
        public Proyecto_IPC2()
            : base("name=Proyecto_IPC2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Detalle_Solitario> Detalle_Solitario { get; set; }
        public virtual DbSet<Detalle_torneo> Detalle_torneo { get; set; }
        public virtual DbSet<Detalle_Versus> Detalle_Versus { get; set; }
        public virtual DbSet<Invitacion> Invitacion { get; set; }
        public virtual DbSet<ListaTorneo> ListaTorneo { get; set; }
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<Solitario> Solitario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Torneo> Torneo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Versus> Versus { get; set; }
    }
}
