//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2_201700841.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public int id_tipo { get; set; }
        public Nullable<int> ganado { get; set; }
        public Nullable<int> perdido { get; set; }
        public Nullable<int> empatado { get; set; }
        public Nullable<int> id_partido { get; set; }
    
        public virtual Partido Partido { get; set; }
    }
}
