//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2_201700841.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versus()
        {
            this.Detalle_Versus = new HashSet<Detalle_Versus>();
        }
    
        public int id_versus { get; set; }
        public Nullable<int> id_invitacion { get; set; }
        public Nullable<int> id_us { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Versus> Detalle_Versus { get; set; }
        public virtual Invitacion Invitacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
