//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2_201700841.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargar_Guardar
    {
        public string Id_partida { get; set; }
        public string NombreUsuario { get; set; }
        public string Id_versus { get; set; }
        public string Id_solitario { get; set; }
    
        public virtual Solitario Solitario { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Versus Versus { get; set; }
    }
}
